### ISSUE TITLE
Why Can't I Use Destructuring Here?

### ISSUE THREAD

**Issue by manavm1990** [manavm1990/real-world-vue#2]
https://github.com/manavm1990/real-world-vue/blob/d457c95e15ded538619cfb458b5b8ff7bac0e906/src/views/EventList.vue#L11

Trying to do:
```javascript
import { getEvents } from "@/services/APIService";
console.log(getEvents); // undefined
```
Yet, `APIService.getEvents()` is just fine... 😖

**Comment by minifyre** [comment]
There are a few issues here (I so wish the JS syntax allowed for destructuring as you're describing though! [maybe someday])

1. If you check the [import syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), you'll see you can't do `{prop: asAlias}` like you can with [variable destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), their syntaxes are merely similar in that you can take some modules/properties of the import/object.
2. The reason this doesn't work, is that you can only `import {something, somethingElse} on items explicitly exported via the `export` keyword inside the given module. 
3. The reason that `APIService.getEvents()` works, is that it exists on the imported module. Also, a word of warning, many methods break when they are destructured from their object (since the `this` context is removed- you'd need manually rebind them with this to destructure them [or you could write a fancy proxy wrapper to do it for you]).
